⭐ Simple Definition

NumPy is a Python library that helps you work with arrays, matrices, and mathematical functions in a fast and efficient way.

🧠 Why we use NumPy?

Because Python lists are slow. NumPy makes calculations:

faster

less memory usage

easy to write mathematical logic

In [1]:
import numpy as np
numpy_array=np.array([1,2,3,4,5,6])
print(numpy_array)


[1 2 3 4 5 6]


1. One Dimensional Array (1D)

It is like a simple list.
Contains elements in single row.

In [2]:
# one dimention array
import numpy as np 
n_1d=np.array([10,20,30,40])
print(n_1d)

[10 20 30 40]


2. Two Dimensional Array (2D)

It looks like a table (matrix)
Rows and Columns.

In [7]:
import numpy as np
n_2d=np.array([[1,2,3],
             [4,5,6],
              [7,8,9]])
print(n_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3. Three Dimensional Array (3D)

Array inside array inside array.
It looks like a cube.

In [2]:
#np.zeros(shape)=Creates an array filled with all zeros

import numpy as np
zeros_array=np.zeros(4)
print(zeros_array)

[0. 0. 0. 0.]


In [17]:
zeros_array=np.zeros((4,4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
import numpy as np
zeros_array=np.zeros(((2,4,4)))
print(zeros_array)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [18]:
#np.ones()=Creates an array filled with all ones.
ones_array=np.ones(9)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
ones_array=np.ones((4,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
ones_3darray=np.ones((3,4,3))
print(ones_3darray)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [14]:
#3. np.full()=Creates an array filled with a specific value.
filled_array=np.full(5,7)
print(filled_array)

[7 7 7 7 7]


In [15]:
filled_array=np.full((2,2),7)
print(filled_array)

[[7 7]
 [7 7]]


In [19]:
filled_array=np.full((2,2,2),7)
print(filled_array)

[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


In [21]:
ones_array=np.ones((4,4,4)) #shape(blocks,rows,columns)
print(ones_array)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [22]:
#np.arange()=creates an array with regularly spaced values (like Python’s range, but for NumPy arrays).
arrang_array=np.arange(0,50,5)
print(arrang_array)

[ 0  5 10 15 20 25 30 35 40 45]


An identity matrix is a square matrix (same number of rows and columns) in which:

All diagonal elements are 1

All other elements are 0

In [23]:
I=np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
#how to find shape of array
#shape find rows and column.
arr_2d = np.array([[1,2,3],
                  [4,5,6]])
print(arr_2d.shape)

(2, 3)


In [26]:
#size= gives total number of elemnts.
arr_2d = np.array([[1,2,3],
                  [4,5,6]])
print(arr_2d.size)

6


In [27]:
#ndim returns how many dimentions are existing
#n(number)+dim(dimension)
numpy_array=np.array([1,2,3,4,5,6])
print(numpy_array.ndim)

1


In [28]:

n_2d=np.array([[1,2,3],
             [4,5,6],
              [7,8,9]])
print(n_2d.ndim)

2


In [32]:
#type method show the type of array
numpy_array=np.array([1,2,37,4+5J,5,6])
print(numpy_array.dtype)


complex128


In [34]:
arr= np.array([1.2,2.5,3.8])
int_array=arr.astype(int) #converty into float to int.
print(int_array)
print(int_array.dtype)


[1 2 3]
int32


In [36]:
#mathematical operations
arr=np.array([10,20,30])
print(arr+5)
print(arr-5)
print(arr*5)
print(arr**2)



[15 25 35]
[ 5 15 25]
[ 50 100 150]
[100 400 900]


In [5]:
n_2d=np.array([[1,2,3],
             [4,5,6],
              [7,8,9]])
print(n_2d + 1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [37]:
#Aggregation Function
#np.sum(array)
#np.mean(array)
#np.min(array)
#np.max(array)
#np.std(array)
#np.var(array)

In [39]:
arr=np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.var(arr))



150
30.0
50
10
14.142135623730951
200.0


In [1]:
1. #Indexing in NumPy

#Indexing means accessing elements of an array using their position.

1.0

In [3]:

import numpy as np
arrr=np.array([10,20,30,40,50])
print(arrr[1])

20


In [4]:
indexing_arr=np.array([[12,43,56],
                      [34,66,78]])
print(indexing_arr[1,2])

78


In [7]:
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])
print(arr[1,1,1])

11


In [12]:
arrr=np.array([10,20,30,40,50,60,70])
print(arrr[2:5])
print(arrr[:4])
print(arrr[-1:2:-1])
print(arrr[-5:-1])
print(arrr[0:-1])
print(arrr[::2])
print(arrr[::-1])



[30 40 50]
[10 20 30 40]
[70 60 50 40]
[30 40 50 60]
[10 20 30 40 50 60]
[10 30 50 70]
[70 60 50 40 30 20 10]


In [14]:
#fancy indexing= selecting multiple elements at ones.
print(arrr[[0,2,4]])

[10 30 50]


In [25]:
#boolean masking = it give data based on conditon
print(arrr[arrr>25])
print(arrr[(arrr>25) & (arrr<60)])
print(arrr[(arrr % 3 == 0)])

[30 40 50 60 70]
[30 40 50]
[30 60]


In [11]:
#Reshaping and manipulating array 
#reshaping means changing dimension without modifing data.
#reshaping does not create copy it gives view.
arr=np.array([1,2,3,4,5,6])
reshaped_2darray=arr.reshape(2,3)
reshaped_3darray= arr.reshape(2,1,3)
print(reshaped_2darray)
print(reshaped_3darray)


[[[1 2 3]]

 [[4 5 6]]]


In [18]:
#flattening array  = it converts multi dimension array into 1d array. 
'''
ravel(), flatten() both doing same work only diff. is ravel gives view and flatten gives copy of array. 
.ravel() --> View          , affects original array
.flatten()-->returns copy  ,does not affect original array
'''

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d.ravel())
print(arr_2d.flatten())


[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [12]:
#adding elemnt in array
'''
syntax=np.insert(array, index, value , asix=None)
array =original array
index = 
value = 
axis =
axis = 0 , row-wise
axis = 1 , cloumn wise
'''
arr = np.array([10,20,30,40,50,60])
print(arr)
new_arr=np.insert(arr,2,100,axis=0)
new_arr2=np.insert(arr,0,5,axis=0)
print(new_arr)
print(new_arr2)


[10 20 30 40 50 60]
[ 10  20 100  30  40  50  60]
[ 5 10 20 30 40 50 60]


In [37]:
arr_2d = np.array([[1,2],[3,4]])
new_arr= np.insert(arr_2d , 1 , [5,6] , axis=0 )
print(new_arr)

[[1 2]
 [5 6]
 [3 4]]


In [38]:
new_arr= np.insert(arr_2d , 1 , [5,6] , axis=1 )
print(new_arr)

[[1 5 2]
 [3 6 4]]


In [39]:
new_arr= np.insert(arr_2d , 1 , [5,6] , axis=None )
print(new_arr)

[1 5 6 2 3 4]


In [42]:
#Append  
arr= np.array([10,20,30])
new_arr = np.append(arr,[40,50,60])
print(new_arr)

[10 20 30 40 50 60]


In [43]:
#Append rows in a 2D array 
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

new_arr = np.append(arr, [[7, 8, 9]], axis=0)

print(new_arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
'''
NumPy concatenate()

np.concatenate() joins two or more arrays along an existing axis.
axis = 0 > vertical stacking
axis = 1 > horizontal stacking

'''
arr1 = np.array([[1,2,3],
               [4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
new_arr= np.concatenate((arr1 , arr2))
print(new_arr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [49]:
#delete() for removing the elements.
#for 1D
arr= np.array([10,20,30,40,50,60])
print(arr)
new_arr=np.delete(arr,0)
print(new_arr)

[10 20 30 40 50 60]
[20 30 40 50 60]


In [14]:
arr_2d=np.array([[1,2,3],[4,5,6]])
new_arr_2d = np.delete(arr_2d, 0, axis=0)
print(new_arr_2d)



[[4 5 6]]


In [56]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1 , arr2)))
print(np.dstack((arr1 , arr2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[[1 4]
  [2 5]
  [3 6]]]


In [57]:
#concatenate → joins arrays WITHOUT creating a new dimension
#✅ stack → joins arrays BY CREATING a new dimension

In [59]:
arr = np.array([10,20,30,40,50,60])
print(np.split(arr,3))

[array([10, 20]), array([30, 40]), array([50, 60])]


In [67]:
#Brodcasting  = by using brodcasting we perform operation on different different and big data size arrays without using loops.


#Broadcasting lets NumPy perform operations on arrays of different shapes by automatically expanding them.

In [62]:
prices = np.array([100,200,300])
discount=10
final_prices=prices-(prices*discount/100)
print(final_prices)

[ 90. 180. 270.]


### brodcasting using single value


In [64]:
arr=np.array([10,20,30])
result=arr*2
print(result)

[20 40 60]


boradcasting type
How numpy works with differ shapes
1. Matching dimension [1,2,3] +[4,5,6] =[5,7,9]
2. expanding single elements [1,2,3]+[10]=[11,12,13]
3. incompatible shapes [1,2,3]+[1,2] = error

In [65]:
#Matching dimension [1,2,3] +[4,5,6] =[5,7,9]
matrix=np.array([[1,2,3],[4,5,6]])#2D
vector=np.array([10,20,30])#1D
result = matrix+vector
print(result)

[[11 22 33]
 [14 25 36]]


In [18]:
#expanding single elements [1,2,3]+[10]
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([10])
print(arr1+arr2)

[11 12 13]


In [66]:
#incompatible shapes [1,2,3]+[1,2] = error
arr1=np.array([[1,2,3],[4,5,6]])#shape(2,3)
arr2=np.array([1,2]) #shape(2)
print(arr1+arr2)

#Solution is .reshape()

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

#vectorization
⭐ What is Vectorization in NumPy?

Vectorization means performing operations on entire arrays at once instead of using loops.

✔ Fast
✔ Simple
✔ Uses optimized C code internally
✔ Removes for loops

In [19]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=arr1+arr2
print(result)

[5 7 9]


In [20]:
arr=np.array([10,20,30])
multipled=arr*3
print(multipled)

[30 60 90]


##Difference in borad casting and vectorization.

⭐ Broadcasting handles different shapes. faster thann loop . 

⭐ Vectorization removes loops and makes operations fast. 100* faster than loop. 

##Handling missing values 

Builtin Function 

np.isnan= detect missing values.

np.nan_to_num() = replace null valued with number.

np.isinf() = detect infinite values.

NaN = not a number.



In [23]:
#np.isnan(array)
import numpy as np

arr = np.array([1,2,np.nan , 4 , np.nan , 6])
print(np.isnan(arr))
print(np.isnan(arr).sum())# counting the missing value


[False False  True False  True False]
2


In [6]:
#np.nan_to_num() = replace null valued with number.
import numpy as np
arr = np.array([1,2,np.nan , 4 , np.nan , 6])
cleaned_arr=np.nan_to_num(arr ,nan=100)
print(cleaned_arr)

[  1.   2. 100.   4. 100.   6.]


In [4]:
#default value is 0
arr = np.array([1,2,np.nan , 4 , np.nan , 6])
cleaned_arr=np.nan_to_num(arr)
print(cleaned_arr)

[1. 2. 0. 4. 0. 6.]


In [7]:
#detect infinite number #np.isinf()
arr=np.array([1,2,np.inf , 4 , -np.inf , 6])
print(np.isinf(arr))

[False False  True False  True False]


In [12]:
#replace infinte values
arr = np.array([1,2,np.inf,4,-np.inf,6])
print(np.isinf(arr).sum())
cleaned_arr = np.nan_to_num(arr , posinf=1000 , neginf=1000)
print(cleaned_arr)


2
[   1.    2. 1000.    4. 1000.    6.]


✅ 🔥 Basic NumPy Interview Questions
1. What is NumPy?

NumPy is a Python library used for numerical computing. It provides fast multi-dimensional arrays and support for mathematical operations on them.

2. What is a NumPy array?

A NumPy array (ndarray) is a fast, continuous block of memory used to store elements of the same data type.

3. How do you create a NumPy array?
import numpy as np
arr = np.array([1, 2, 3])

4. What is the difference between a Python list and a NumPy array?

Python List             	         NumPy Array
1Stores different data types	     Only same data type
2.Slow	                             Very fast
3.No vectorization	                 Supports vectorization

5. How do you check the shape and data type of an array?
arr.shape
arr.dtype

6. How to create arrays of zeros and ones?
np.zeros((3,3))
np.ones((2,4))

7. How do you generate a range of numbers?
np.arange(1, 10, 2)
np.linspace(0, 1, 5)

✅ 🔥 Intermediate NumPy Interview Questions
8. What is broadcasting in NumPy?

Broadcasting is the mechanism that allows NumPy to perform operations on arrays of different shapes.

9. What is vectorization?

Vectorization means performing operations without loops, directly on arrays → faster execution.

Example:

arr * 2

10. How to reshape an array?
arr.reshape(3, 4)

11. Difference between reshape() and ravel()?

reshape() → returns a new array with a changed shape.

ravel() → returns a flattened, 1D array.

12. How to concatenate arrays?
np.concatenate([a, b], axis=0)

13. Difference: concatenate vs stack

concatenate → joins along existing axis

stack → creates a new axis

Example:

np.stack([a, b])

14. How do you index/slice a NumPy array?
arr[1:4]
arr[:, 2]
arr[2, 3]

15. What is boolean masking?

Filtering array using boolean conditions:

arr[arr > 10]

16. How to find NaN values?
np.isnan(arr)
np.isnan(arr).sum()

17. How to handle infinity values?
np.isinf(arr)
np.isposinf(arr)
np.isneginf(arr)

18. How to find mean, median, standard deviation?
np.mean(arr)
np.median(arr)
np.std(arr)

✅ 🔥 Advanced NumPy Interview Questions
19. What is the difference between copy() and view()?

copy → creates new memory

view → shares memory (changes reflect in both)

20. How does NumPy achieve high speed?

✔ Vectorization
✔ Broadcasting
✔ Implemented in C
✔ Uses contiguous memory blocks

21. What is an axis in NumPy?

Axis = direction of operation.

Axis 0 → rows

Axis 1 → columns

Example:

arr.sum(axis=0)

22. Explain np.where()

Used to return elements based on condition.

np.where(arr > 5, 1, 0)

23. Explain np.unique()

Returns unique values and counts:

np.unique(arr, return_counts=True)

24. Explain broadcasting rules

Arrays are compatible if:

Dimensions match, or

One of them is 1

25. What is memory layout (C vs F order)?

C order → row-major

F order → column-major

Used in:

arr.reshape(3,3, order='F')

